### ISSUE TITLE
On sundays show monday

### ISSUE THREAD

**Issue by dbrgn** [gysel/HSR-Timetable#1]
On a sunday, show the timetable for monday.

**Comment by gysel** [comment]
What is your suggested behaviour?

**Comment by dbrgn** [comment]
Habs ja geschrieben :P Am Sonntag den Montagsstundenplan anzeigen.

**Comment by gysel** [comment]
hehe, falsch gelesen.

**Comment by gysel** [comment]
done. will be shipped with the next release.
