### ISSUE TITLE
Gebäudeplan einbinden

### ISSUE THREAD

**Issue by dbrgn** [gysel/HSR-Timetable#2]
Gebäudeplan einbinden, damit man zB auf einer Karte sehen kann, wo das gesuchte Zimmer ist.

Einfache Variante - einfach Gebäudenamen anzeigen. Erweiterte Möglichkeiten würde OpenStreetmap bieten, da sind alle Gebäude und Zimmer mit Ebeneninformationen erfasst.

**Comment by gysel** [comment]
Gute Idee - hatte ich auch schon.

Beinhaltet OSM die Informationen zu den Zimmern?

**Comment by dbrgn** [comment]
Jep.

http://www.openstreetmap.org/?lat=47.22323&lon=8.817358&zoom=18&layers=M

Rechts aufs Plus klicken und dann "Daten" aktivieren.

**Comment by gysel** [comment]
siehe auch:
http://labs.geometa.info/campusmap/

**Comment by dbrgn** [comment]
Das hab ich gesucht :)

2012/2/23 theScythe
reply@reply.github.com:

**Comment by dbrgn** [comment]
Mach mal chli fürschi! :smile:

**Comment by gysel** [comment]
fuuu :p
